<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Aliases for the whitelisted classes. For more information see:
// https://github.com/humbug/php-scoper/blob/master/README.md#class-whitelisting
if (!class_exists('Google_Service', false)) {
    class_exists('NF_FU_VENDOR\Google_Service');
}
if (!class_exists('Google_AccessToken_Revoke', false)) {
    class_exists('NF_FU_VENDOR\Google_AccessToken_Revoke');
}
if (!class_exists('Google_AccessToken_Verify', false)) {
    class_exists('NF_FU_VENDOR\Google_AccessToken_Verify');
}
if (!class_exists('Google_Model', false)) {
    class_exists('NF_FU_VENDOR\Google_Model');
}
if (!class_exists('Google_Utils_UriTemplate', false)) {
    class_exists('NF_FU_VENDOR\Google_Utils_UriTemplate');
}
if (!class_exists('Google_AuthHandler_Guzzle6AuthHandler', false)) {
    class_exists('NF_FU_VENDOR\Google_AuthHandler_Guzzle6AuthHandler');
}
if (!class_exists('Google_AuthHandler_Guzzle5AuthHandler', false)) {
    class_exists('NF_FU_VENDOR\Google_AuthHandler_Guzzle5AuthHandler');
}
if (!class_exists('Google_AuthHandler_AuthHandlerFactory', false)) {
    class_exists('NF_FU_VENDOR\Google_AuthHandler_AuthHandlerFactory');
}
if (!class_exists('Google_Http_Batch', false)) {
    class_exists('NF_FU_VENDOR\Google_Http_Batch');
}
if (!class_exists('Google_Http_MediaFileUpload', false)) {
    class_exists('NF_FU_VENDOR\Google_Http_MediaFileUpload');
}
if (!class_exists('Google_Http_REST', false)) {
    class_exists('NF_FU_VENDOR\Google_Http_REST');
}
if (!class_exists('Google_Task_Retryable', false)) {
    class_exists('NF_FU_VENDOR\Google_Task_Retryable');
}
if (!class_exists('Google_Task_Exception', false)) {
    class_exists('NF_FU_VENDOR\Google_Task_Exception');
}
if (!class_exists('Google_Task_Runner', false)) {
    class_exists('NF_FU_VENDOR\Google_Task_Runner');
}
if (!class_exists('Google_Collection', false)) {
    class_exists('NF_FU_VENDOR\Google_Collection');
}
if (!class_exists('Google_Service_Exception', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Exception');
}
if (!class_exists('Google_Service_Resource', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Resource');
}
if (!class_exists('Google_Exception', false)) {
    class_exists('NF_FU_VENDOR\Google_Exception');
}
if (!class_exists('Google_Client', false)) {
    class_exists('NF_FU_VENDOR\Google_Client');
}
if (!class_exists('Google_Service_Oauth2_Userinfoplus', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Userinfoplus');
}
if (!class_exists('Google_Service_Oauth2_Tokeninfo', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Tokeninfo');
}
if (!class_exists('Google_Service_Oauth2_Jwk', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Jwk');
}
if (!class_exists('Google_Service_Oauth2_JwkKeys', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_JwkKeys');
}
if (!class_exists('Google_Service_Oauth2_Resource_UserinfoV2Me', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Resource_UserinfoV2Me');
}
if (!class_exists('Google_Service_Oauth2_Resource_Userinfo', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Resource_Userinfo');
}
if (!class_exists('Google_Service_Oauth2_Resource_UserinfoV2', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2_Resource_UserinfoV2');
}
if (!class_exists('Google_Service_DriveActivity_Domain', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Domain');
}
if (!class_exists('Google_Service_DriveActivity_KnownUser', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_KnownUser');
}
if (!class_exists('Google_Service_DriveActivity_NoConsolidation', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_NoConsolidation');
}
if (!class_exists('Google_Service_DriveActivity_DriveReference', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveReference');
}
if (!class_exists('Google_Service_DriveActivity_Owner', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Owner');
}
if (!class_exists('Google_Service_DriveActivity_Group', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Group');
}
if (!class_exists('Google_Service_DriveActivity_Rename', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Rename');
}
if (!class_exists('Google_Service_DriveActivity_Post', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Post');
}
if (!class_exists('Google_Service_DriveActivity_Action', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Action');
}
if (!class_exists('Google_Service_DriveActivity_Move', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Move');
}
if (!class_exists('Google_Service_DriveActivity_DeletedUser', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DeletedUser');
}
if (!class_exists('Google_Service_DriveActivity_DriveactivityNew', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveactivityNew');
}
if (!class_exists('Google_Service_DriveActivity_QueryDriveActivityResponse', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_QueryDriveActivityResponse');
}
if (!class_exists('Google_Service_DriveActivity_TimeRange', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_TimeRange');
}
if (!class_exists('Google_Service_DriveActivity_Impersonation', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Impersonation');
}
if (!class_exists('Google_Service_DriveActivity_DriveItemReference', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveItemReference');
}
if (!class_exists('Google_Service_DriveActivity_DriveactivityFile', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveactivityFile');
}
if (!class_exists('Google_Service_DriveActivity_SettingsChange', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_SettingsChange');
}
if (!class_exists('Google_Service_DriveActivity_User', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_User');
}
if (!class_exists('Google_Service_DriveActivity_SystemEvent', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_SystemEvent');
}
if (!class_exists('Google_Service_DriveActivity_TeamDrive', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_TeamDrive');
}
if (!class_exists('Google_Service_DriveActivity_DataLeakPreventionChange', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DataLeakPreventionChange');
}
if (!class_exists('Google_Service_DriveActivity_Create', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Create');
}
if (!class_exists('Google_Service_DriveActivity_Target', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Target');
}
if (!class_exists('Google_Service_DriveActivity_TargetReference', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_TargetReference');
}
if (!class_exists('Google_Service_DriveActivity_DriveFile', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveFile');
}
if (!class_exists('Google_Service_DriveActivity_Suggestion', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Suggestion');
}
if (!class_exists('Google_Service_DriveActivity_Actor', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Actor');
}
if (!class_exists('Google_Service_DriveActivity_DriveItem', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveItem');
}
if (!class_exists('Google_Service_DriveActivity_RestrictionChange', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_RestrictionChange');
}
if (!class_exists('Google_Service_DriveActivity_Folder', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Folder');
}
if (!class_exists('Google_Service_DriveActivity_ActionDetail', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_ActionDetail');
}
if (!class_exists('Google_Service_DriveActivity_Upload', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Upload');
}
if (!class_exists('Google_Service_DriveActivity_DriveActivity', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveActivity');
}
if (!class_exists('Google_Service_DriveActivity_Comment', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Comment');
}
if (!class_exists('Google_Service_DriveActivity_FileComment', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_FileComment');
}
if (!class_exists('Google_Service_DriveActivity_Restore', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Restore');
}
if (!class_exists('Google_Service_DriveActivity_Drive', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Drive');
}
if (!class_exists('Google_Service_DriveActivity_Delete', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Delete');
}
if (!class_exists('Google_Service_DriveActivity_Anyone', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Anyone');
}
if (!class_exists('Google_Service_DriveActivity_Edit', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Edit');
}
if (!class_exists('Google_Service_DriveActivity_ConsolidationStrategy', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_ConsolidationStrategy');
}
if (!class_exists('Google_Service_DriveActivity_Administrator', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Administrator');
}
if (!class_exists('Google_Service_DriveActivity_PermissionChange', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_PermissionChange');
}
if (!class_exists('Google_Service_DriveActivity_Resource_Activity', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Resource_Activity');
}
if (!class_exists('Google_Service_DriveActivity_Assignment', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Assignment');
}
if (!class_exists('Google_Service_DriveActivity_UnknownUser', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_UnknownUser');
}
if (!class_exists('Google_Service_DriveActivity_DriveFolder', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_DriveFolder');
}
if (!class_exists('Google_Service_DriveActivity_QueryDriveActivityRequest', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_QueryDriveActivityRequest');
}
if (!class_exists('Google_Service_DriveActivity_ApplicationReference', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_ApplicationReference');
}
if (!class_exists('Google_Service_DriveActivity_TeamDriveReference', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_TeamDriveReference');
}
if (!class_exists('Google_Service_DriveActivity_Permission', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Permission');
}
if (!class_exists('Google_Service_DriveActivity_AnonymousUser', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_AnonymousUser');
}
if (!class_exists('Google_Service_DriveActivity_Copy', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Copy');
}
if (!class_exists('Google_Service_DriveActivity_Legacy', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity_Legacy');
}
if (!class_exists('Google_Service_Oauth2', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Oauth2');
}
if (!class_exists('Google_Service_DriveActivity', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_DriveActivity');
}
if (!class_exists('Google_Service_Drive', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive');
}
if (!class_exists('Google_Service_Drive_PermissionList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_PermissionList');
}
if (!class_exists('Google_Service_Drive_Revision', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Revision');
}
if (!class_exists('Google_Service_Drive_PermissionPermissionDetails', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_PermissionPermissionDetails');
}
if (!class_exists('Google_Service_Drive_DriveFileContentHintsThumbnail', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileContentHintsThumbnail');
}
if (!class_exists('Google_Service_Drive_AboutTeamDriveThemes', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_AboutTeamDriveThemes');
}
if (!class_exists('Google_Service_Drive_DriveFileContentHints', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileContentHints');
}
if (!class_exists('Google_Service_Drive_StartPageToken', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_StartPageToken');
}
if (!class_exists('Google_Service_Drive_TeamDriveCapabilities', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_TeamDriveCapabilities');
}
if (!class_exists('Google_Service_Drive_DriveFileImageMediaMetadataLocation', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileImageMediaMetadataLocation');
}
if (!class_exists('Google_Service_Drive_DriveRestrictions', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveRestrictions');
}
if (!class_exists('Google_Service_Drive_DriveFileImageMediaMetadata', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileImageMediaMetadata');
}
if (!class_exists('Google_Service_Drive_PermissionTeamDrivePermissionDetails', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_PermissionTeamDrivePermissionDetails');
}
if (!class_exists('Google_Service_Drive_DriveList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveList');
}
if (!class_exists('Google_Service_Drive_Change', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Change');
}
if (!class_exists('Google_Service_Drive_DriveFileVideoMediaMetadata', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileVideoMediaMetadata');
}
if (!class_exists('Google_Service_Drive_TeamDriveBackgroundImageFile', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_TeamDriveBackgroundImageFile');
}
if (!class_exists('Google_Service_Drive_DriveBackgroundImageFile', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveBackgroundImageFile');
}
if (!class_exists('Google_Service_Drive_User', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_User');
}
if (!class_exists('Google_Service_Drive_CommentQuotedFileContent', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_CommentQuotedFileContent');
}
if (!class_exists('Google_Service_Drive_DriveFileCapabilities', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFileCapabilities');
}
if (!class_exists('Google_Service_Drive_TeamDrive', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_TeamDrive');
}
if (!class_exists('Google_Service_Drive_Reply', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Reply');
}
if (!class_exists('Google_Service_Drive_GeneratedIds', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_GeneratedIds');
}
if (!class_exists('Google_Service_Drive_DriveFile', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveFile');
}
if (!class_exists('Google_Service_Drive_ReplyList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_ReplyList');
}
if (!class_exists('Google_Service_Drive_Channel', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Channel');
}
if (!class_exists('Google_Service_Drive_Comment', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Comment');
}
if (!class_exists('Google_Service_Drive_TeamDriveRestrictions', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_TeamDriveRestrictions');
}
if (!class_exists('Google_Service_Drive_TeamDriveList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_TeamDriveList');
}
if (!class_exists('Google_Service_Drive_FileList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_FileList');
}
if (!class_exists('Google_Service_Drive_Drive', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Drive');
}
if (!class_exists('Google_Service_Drive_DriveCapabilities', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_DriveCapabilities');
}
if (!class_exists('Google_Service_Drive_AboutDriveThemes', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_AboutDriveThemes');
}
if (!class_exists('Google_Service_Drive_RevisionList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_RevisionList');
}
if (!class_exists('Google_Service_Drive_CommentList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_CommentList');
}
if (!class_exists('Google_Service_Drive_Resource_Replies', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Replies');
}
if (!class_exists('Google_Service_Drive_Resource_Permissions', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Permissions');
}
if (!class_exists('Google_Service_Drive_Resource_Comments', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Comments');
}
if (!class_exists('Google_Service_Drive_Resource_Files', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Files');
}
if (!class_exists('Google_Service_Drive_Resource_Channels', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Channels');
}
if (!class_exists('Google_Service_Drive_Resource_Drives', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Drives');
}
if (!class_exists('Google_Service_Drive_Resource_Revisions', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Revisions');
}
if (!class_exists('Google_Service_Drive_Resource_Changes', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Changes');
}
if (!class_exists('Google_Service_Drive_Resource_About', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_About');
}
if (!class_exists('Google_Service_Drive_Resource_Teamdrives', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Resource_Teamdrives');
}
if (!class_exists('Google_Service_Drive_About', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_About');
}
if (!class_exists('Google_Service_Drive_AboutStorageQuota', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_AboutStorageQuota');
}
if (!class_exists('Google_Service_Drive_Permission', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_Permission');
}
if (!class_exists('Google_Service_Drive_ChangeList', false)) {
    class_exists('NF_FU_VENDOR\Google_Service_Drive_ChangeList');
}
if (!class_exists('ComposerAutoloaderInitba654e2f862251e50192260b3bb269fe', false)) {
    class_exists('NF_FU_VENDOR\ComposerAutoloaderInitba654e2f862251e50192260b3bb269fe');
}
if (!class_exists('JsonException', false)) {
    class_exists('NF_FU_VENDOR\JsonException');
}

// Functions whitelisting. For more information see:
// https://github.com/humbug/php-scoper/blob/master/README.md#functions-whitelisting
if (!function_exists('phpseclib_safe_serialize')) {
    function phpseclib_safe_serialize() {
        return \NF_FU_VENDOR\phpseclib_safe_serialize(...func_get_args());
    }
}
if (!function_exists('runSuite')) {
    function runSuite() {
        return \NF_FU_VENDOR\runSuite(...func_get_args());
    }
}
if (!function_exists('runCase')) {
    function runCase() {
        return \NF_FU_VENDOR\runCase(...func_get_args());
    }
}
if (!function_exists('uri_template')) {
    function uri_template() {
        return \NF_FU_VENDOR\uri_template(...func_get_args());
    }
}
if (!function_exists('parseArgs')) {
    function parseArgs() {
        return \NF_FU_VENDOR\parseArgs(...func_get_args());
    }
}
if (!function_exists('showHelp')) {
    function showHelp() {
        return \NF_FU_VENDOR\showHelp(...func_get_args());
    }
}
if (!function_exists('formatErrorMessage')) {
    function formatErrorMessage() {
        return \NF_FU_VENDOR\formatErrorMessage(...func_get_args());
    }
}
if (!function_exists('oauth2client_php_autoload')) {
    function oauth2client_php_autoload() {
        return \NF_FU_VENDOR\oauth2client_php_autoload(...func_get_args());
    }
}
if (!function_exists('RuntimeException')) {
    function RuntimeException() {
        return \NF_FU_VENDOR\RuntimeException(...func_get_args());
    }
}
if (!function_exists('intVal')) {
    function intVal() {
        return \NF_FU_VENDOR\intVal(...func_get_args());
    }
}
if (!function_exists('composerRequireba654e2f862251e50192260b3bb269fe')) {
    function composerRequireba654e2f862251e50192260b3bb269fe() {
        return \NF_FU_VENDOR\composerRequireba654e2f862251e50192260b3bb269fe(...func_get_args());
    }
}
if (!function_exists('includeIfExists')) {
    function includeIfExists() {
        return \NF_FU_VENDOR\includeIfExists(...func_get_args());
    }
}
if (!function_exists('zend_monitor_custom_event')) {
    function zend_monitor_custom_event() {
        return \NF_FU_VENDOR\zend_monitor_custom_event(...func_get_args());
    }
}
if (!function_exists('setproctitle')) {
    function setproctitle() {
        return \NF_FU_VENDOR\setproctitle(...func_get_args());
    }
}

return $loader;
